In [1]:
import numpy as np 

In [3]:
arr= np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
slice_of_arr =arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [8]:
import numpy as np
arr2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [10]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [16]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
bool_arr = arr>5

In [20]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [24]:
arr_2d = np.arange(50).reshape(5,10)

In [26]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])